spring.application.name=backend

spring.datasource.url=jdbc:mysql://@yamanote.proxy.rlwy.net:15169/railway
spring.datasource.username=root
spring.datasource.password=JQWocjNtzqvYSnPlHQSQghLtOLNGgZuZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


